#spring:
#  jms:
#    template:
#      default-destination: pizzaHot.order.queue
#  activemq:
#    user: sa
#    password: sa
#    embedded:
#      enabled: false
#    broker-url: tcp://localhost:61616