#spring:
#  jms:
#    template:
#      default-destination: pizzaHot.order.queue
#  artemis:
#    user: sa
#    password: sa
#    embedded:
#      enabled: false
#    broker-url: tcp://localhost:61616
#
#
#logging:
#  level:
#    org.springframework.jms: DEBUG
#
#server:
#  port: 7070